using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WhatsAppCampaignApi.Migrations
{
    /// <inheritdoc />
    public partial class AddChatFeature : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ChatConversations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ContactId" integer NOT NULL,
                    "WabaPhoneNumberId" integer,
                    "LastMessageText" character varying(1024),
                    "LastMessageAt" timestamp with time zone,
                    "UnreadCount" integer NOT NULL DEFAULT 0,
                    "IsArchived" boolean NOT NULL DEFAULT false,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_ChatConversations" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "ChatMessages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ConversationId" integer NOT NULL,
                    "CampaignId" integer,
                    "CampaignContactId" integer,
                    "WhatsAppMessageId" character varying(200),
                    "Direction" character varying(50) NOT NULL,
                    "Status" character varying(50) NOT NULL,
                    "Text" character varying(4096) NOT NULL,
                    "IsTemplate" boolean NOT NULL DEFAULT false,
                    "ErrorMessage" character varying(1000),
                    "SentAt" timestamp with time zone,
                    "DeliveredAt" timestamp with time zone,
                    "ReadAt" timestamp with time zone,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id")
                );

                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "ContactId" integer NOT NULL DEFAULT 0;
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "WabaPhoneNumberId" integer;
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "LastMessageText" character varying(1024);
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "LastMessageAt" timestamp with time zone;
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "UnreadCount" integer NOT NULL DEFAULT 0;
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "IsArchived" boolean NOT NULL DEFAULT false;
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "ChatConversations" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW();

                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "ConversationId" integer NOT NULL DEFAULT 0;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "CampaignId" integer;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "CampaignContactId" integer;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "WhatsAppMessageId" character varying(200);
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "Direction" character varying(50) NOT NULL DEFAULT 'Outgoing';
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "Status" character varying(50) NOT NULL DEFAULT 'Pending';
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "Text" character varying(4096) NOT NULL DEFAULT '';
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "IsTemplate" boolean NOT NULL DEFAULT false;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "ErrorMessage" character varying(1000);
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "SentAt" timestamp with time zone;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "DeliveredAt" timestamp with time zone;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "ReadAt" timestamp with time zone;
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "ChatMessages" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW();

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatConversations_ContactId"
                    ON "ChatConversations" ("ContactId");

                CREATE INDEX IF NOT EXISTS "IX_ChatConversations_LastMessageAt"
                    ON "ChatConversations" ("LastMessageAt");

                CREATE INDEX IF NOT EXISTS "IX_ChatConversations_WabaPhoneNumberId"
                    ON "ChatConversations" ("WabaPhoneNumberId");

                CREATE INDEX IF NOT EXISTS "IX_ChatMessages_CampaignContactId"
                    ON "ChatMessages" ("CampaignContactId");

                CREATE INDEX IF NOT EXISTS "IX_ChatMessages_CampaignId"
                    ON "ChatMessages" ("CampaignId");

                CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_CreatedAt"
                    ON "ChatMessages" ("ConversationId", "CreatedAt");

                CREATE INDEX IF NOT EXISTS "IX_ChatMessages_WhatsAppMessageId"
                    ON "ChatMessages" ("WhatsAppMessageId");

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatConversations_Contacts_ContactId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM "ChatConversations" c
                        LEFT JOIN "Contacts" ct ON ct."Id" = c."ContactId"
                        WHERE ct."Id" IS NULL
                    ) THEN
                        ALTER TABLE "ChatConversations"
                        ADD CONSTRAINT "FK_ChatConversations_Contacts_ContactId"
                        FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatConversations_PhoneNumbers_WabaPhoneNumberId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM "ChatConversations" c
                        LEFT JOIN "PhoneNumbers" p ON p."Id" = c."WabaPhoneNumberId"
                        WHERE c."WabaPhoneNumberId" IS NOT NULL AND p."Id" IS NULL
                    ) THEN
                        ALTER TABLE "ChatConversations"
                        ADD CONSTRAINT "FK_ChatConversations_PhoneNumbers_WabaPhoneNumberId"
                        FOREIGN KEY ("WabaPhoneNumberId") REFERENCES "PhoneNumbers" ("Id") ON DELETE SET NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatMessages_CampaignContacts_CampaignContactId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM "ChatMessages" m
                        LEFT JOIN "CampaignContacts" cc ON cc."Id" = m."CampaignContactId"
                        WHERE m."CampaignContactId" IS NOT NULL AND cc."Id" IS NULL
                    ) THEN
                        ALTER TABLE "ChatMessages"
                        ADD CONSTRAINT "FK_ChatMessages_CampaignContacts_CampaignContactId"
                        FOREIGN KEY ("CampaignContactId") REFERENCES "CampaignContacts" ("Id") ON DELETE SET NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatMessages_Campaigns_CampaignId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM "ChatMessages" m
                        LEFT JOIN "Campaigns" c ON c."Id" = m."CampaignId"
                        WHERE m."CampaignId" IS NOT NULL AND c."Id" IS NULL
                    ) THEN
                        ALTER TABLE "ChatMessages"
                        ADD CONSTRAINT "FK_ChatMessages_Campaigns_CampaignId"
                        FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE SET NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatMessages_ChatConversations_ConversationId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM "ChatMessages" m
                        LEFT JOIN "ChatConversations" c ON c."Id" = m."ConversationId"
                        WHERE c."Id" IS NULL
                    ) THEN
                        ALTER TABLE "ChatMessages"
                        ADD CONSTRAINT "FK_ChatMessages_ChatConversations_ConversationId"
                        FOREIGN KEY ("ConversationId") REFERENCES "ChatConversations" ("Id") ON DELETE CASCADE;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "ChatMessages";
                DROP TABLE IF EXISTS "ChatConversations";
                """);
        }
    }
}
